----------------------------------------------------------------------  Committing in .
 Modified Files:
 	Makefile.in aclocal.m4 configure configure.ac
 	Examples/Makefile.in src/Makefile.in
 Added Files:
 	config/tac_arg_header_check.m4
 ----------------------------------------------------------------------
Fixing a problem with the noxloca option that required us to have
-DHAVE_CONFIG_H in the list of configure arguments.  I wrote a new
macro for header checking based on one that NOX currently uses, but
I removed unnecessary complexity for our case.

For Tramonto to properly configure under the new setup when
--with-noxloca is used, it is necessary to do one of two things:

1) (Preferred) Use --with-incdirs= instead of --with-cxxflags and
--with-cflags for passing the -I that includes the path to the
installed Trilinos headers.  This is the way that Trilinos generally
gets include info.

2) In addition to --with-cxxflags and --with-cflags, the -I information
for Trilinos headers also needs to be passed to CPPFLAGS.

We could also think about moving in the direction of a --with-trilinos
option, but that would prove unnecessary if we package Tramonto with
a subset of Trilinos as we spoke about last week at SJU.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7562,70 +7562,31 @@ fi
 
 if test "X$ac_cv_use_noxloca" != "Xno"; then
 
-  if test "${ac_cv_header_LOCA_H+set}" = set; then
-  echo "$as_me:$LINENO: checking for LOCA.H" >&5
+
+  save_CPPFLAGS=$CPPFLAGS
+  done=no
+
+echo "$as_me:$LINENO: checking for LOCA.H" >&5
 echo $ECHO_N "checking for LOCA.H... $ECHO_C" >&6
-if test "${ac_cv_header_LOCA_H+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_LOCA_H" >&5
-echo "${ECHO_T}$ac_cv_header_LOCA_H" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking LOCA.H usability" >&5
-echo $ECHO_N "checking LOCA.H usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
+
+  # First try the directories we already have
+  CPPFLAGS="$save_CPPFLAGS $ABS_TRILINOS_CPPFLAGS"
+  cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-$ac_includes_default
-#include <LOCA.H>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_header_compiler=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
+#undef PACKAGE
+#undef PACKAGE_NAME
+#undef PACKAGE_BUGREPORT
+#undef PACKAGE_STRING
+#undef PACKAGE_TARNAME
+#undef PACKAGE_VERSION
+#undef VERSION
+#include "LOCA.H"
 
-# Is the header present?
-echo "$as_me:$LINENO: checking LOCA.H presence" >&5
-echo $ECHO_N "checking LOCA.H presence... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <LOCA.H>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -7645,70 +7606,30 @@ else
   ac_cpp_err=yes
 fi
 if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
+  done=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-  ac_header_preproc=no
+
 fi
 rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
+  CPPFLAGS=$save_CPPFLAGS
 
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: LOCA.H: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: LOCA.H: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: LOCA.H: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: LOCA.H: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: LOCA.H: present but cannot be compiled" >&5
-echo "$as_me: WARNING: LOCA.H: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: LOCA.H:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: LOCA.H:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: LOCA.H: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: LOCA.H: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: LOCA.H:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: LOCA.H:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: LOCA.H: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: LOCA.H: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: LOCA.H: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: LOCA.H: in the future, the compiler will take precedence" >&2;}
-    (
-      cat <<\_ASBOX
-## --------------------------------- ##
-## Report this to ljfrink@sandia.gov ##
-## --------------------------------- ##
-_ASBOX
-    ) |
-      sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-esac
-echo "$as_me:$LINENO: checking for LOCA.H" >&5
-echo $ECHO_N "checking for LOCA.H... $ECHO_C" >&6
-if test "${ac_cv_header_LOCA_H+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_LOCA_H=$ac_header_preproc
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_LOCA_H" >&5
-echo "${ECHO_T}$ac_cv_header_LOCA_H" >&6
-
-fi
-if test $ac_cv_header_LOCA_H = yes; then
-  LIBS="-lnox -lloca $LIBS"
-else
-  { { echo "$as_me:$LINENO: error: Cannot find LOCA header file.
-See \`config.log' for more details." >&5
-echo "$as_me: error: Cannot find LOCA header file.
-See \`config.log' for more details." >&2;}
+  if test $done = no; then
+    echo "------"
+    echo "Cannot preprocess the include file LOCA.H."
+    echo "Try --with-incdir=\"-I<dir1> -I<dir2>\""
+    echo "------"
+    { { echo "$as_me:$LINENO: error: Cannot find " >&5
+echo "$as_me: error: Cannot find " >&2;}
    { (exit 1); exit 1; }; }
-fi
+  else
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  fi
 
+  LIBS="-lnox -lloca $LIBS"
 
 fi
 
