----------------------------------------------------------------------  Committing in .
 Modified Files:
 	Makefile.in aclocal.m4 configure configure.ac
 	Examples/Makefile.in Examples/test_script src/Makefile.am
 	src/Makefile.in src/Tramonto_config.h.in
 ----------------------------------------------------------------------
I am making a few changes:

1) I added a --with-noxloca option for Andy Salinger.  It doesn't do
anything yet because Andy has to add the files to be conditionally
compiled to src/Makefile.am.

2) Updated the list of Fortran compilers to be consistent with Trilinos.
The most important addition was to add gfortran, since that is the
replacement for f77 for GCC 4.x and beyond.

3) Updated Examples/test_script.  It doesn't work completely yet, but
I am trying to get more examples working for possible use with the
test harness in the future.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot RANLIB ac_ct_RANLIB CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE F77 FFLAGS ac_ct_F77 FLIBS CPP EGREP CXXCPP BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BLAS_LIBS LAPACK_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot RANLIB ac_ct_RANLIB CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE F77 FFLAGS ac_ct_F77 FLIBS CPP EGREP CXXCPP BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE HAVE_NOXLOCA_TRUE HAVE_NOXLOCA_FALSE BLAS_LIBS LAPACK_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -909,6 +909,8 @@ Optional Packages:
   --with-incdirs          additional directories containing include files:
                           will prepend to search here for includes, use -Idir
                           format
+  --with-noxloca          Enable NOX and LOCA interface support (default is
+                          no)
   --with-blas=<lib>       use BLAS library <lib>
   --with-lapack=<lib>     use LAPACK library <lib>
 
@@ -3409,7 +3411,7 @@ ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
 ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f77_compiler_gnu
 if test -n "$ac_tool_prefix"; then
-  for ac_prog in mpif77 f77 g77 f90 xlf90 f95
+  for ac_prog in mpif77 f77 g77 gfortran f90 xlf90 f95
   do
     # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
 set dummy $ac_tool_prefix$ac_prog; ac_word=$2
@@ -3451,7 +3453,7 @@ fi
 fi
 if test -z "$F77"; then
   ac_ct_F77=$F77
-  for ac_prog in mpif77 f77 g77 f90 xlf90 f95
+  for ac_prog in mpif77 f77 g77 gfortran f90 xlf90 f95
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -3496,7 +3498,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3499:" \
+echo "$as_me:3501:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -3766,7 +3768,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:3769: \"$ac_link\") >&5
+(eval echo $as_me:3771: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -3844,7 +3846,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:3847: \"$ac_link\") >&5
+(eval echo $as_me:3849: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5049,6 +5051,42 @@ echo "${ECHO_T}no" >&6
 
 fi;
 
+
+
+
+# Check whether --with-noxloca or --without-noxloca was given.
+if test "${with_noxloca+set}" = set; then
+  withval="$with_noxloca"
+  ac_cv_use_noxloca=$withval
+else
+  ac_cv_use_noxloca=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use noxloca" >&5
+echo $ECHO_N "checking whether to use noxloca... $ECHO_C" >&6
+
+if test "X$ac_cv_use_noxloca" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_NOXLOCA
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_noxloca" != "Xno"; then
+  HAVE_NOXLOCA_TRUE=
+  HAVE_NOXLOCA_FALSE='#'
+else
+  HAVE_NOXLOCA_TRUE='#'
+  HAVE_NOXLOCA_FALSE=
+fi
 
 
 
@@ -7522,6 +7560,168 @@ See \`config.log' for more details." >&2;}
 fi
 
 
+if test "X$ac_cv_use_noxloca" != "Xno"; then
+
+  if test "${ac_cv_header_LOCA_H+set}" = set; then
+  echo "$as_me:$LINENO: checking for LOCA.H" >&5
+echo $ECHO_N "checking for LOCA.H... $ECHO_C" >&6
+if test "${ac_cv_header_LOCA_H+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_LOCA_H" >&5
+echo "${ECHO_T}$ac_cv_header_LOCA_H" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking LOCA.H usability" >&5
+echo $ECHO_N "checking LOCA.H usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <LOCA.H>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking LOCA.H presence" >&5
+echo $ECHO_N "checking LOCA.H presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <LOCA.H>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: LOCA.H: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: LOCA.H: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: LOCA.H: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: LOCA.H: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: LOCA.H: present but cannot be compiled" >&5
+echo "$as_me: WARNING: LOCA.H: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: LOCA.H:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: LOCA.H:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: LOCA.H: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: LOCA.H: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: LOCA.H:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: LOCA.H:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: LOCA.H: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: LOCA.H: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: LOCA.H: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: LOCA.H: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## --------------------------------- ##
+## Report this to ljfrink@sandia.gov ##
+## --------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for LOCA.H" >&5
+echo $ECHO_N "checking for LOCA.H... $ECHO_C" >&6
+if test "${ac_cv_header_LOCA_H+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_LOCA_H=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_LOCA_H" >&5
+echo "${ECHO_T}$ac_cv_header_LOCA_H" >&6
+
+fi
+if test $ac_cv_header_LOCA_H = yes; then
+  LIBS="-lnox -lloca $LIBS"
+else
+  { { echo "$as_me:$LINENO: error: Cannot find LOCA header file.
+See \`config.log' for more details." >&5
+echo "$as_me: error: Cannot find LOCA header file.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+fi
+
+else
+
+LIBS="-laztecoo -ltriutils -lifpack -lepetraext -lepetra -lteuchos $MPI_LIBS $LAPACK_LIBS  $BLAS_LIBS $LIBS $FLIBS"
+
+if test "X$ac_cv_use_noxloca" != "Xno"; then
+
+  LIBS="-lnox -lloca $LIBS"
+
+fi
+
 fi
 
 
@@ -7651,6 +7851,13 @@ if test -z "${BUILD_EXAMPLES_TRUE}" && test -z "${BUILD_EXAMPLES_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_NOXLOCA_TRUE}" && test -z "${HAVE_NOXLOCA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_NOXLOCA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_NOXLOCA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -8256,6 +8463,8 @@ s,@EGREP@,$EGREP,;t t
 s,@CXXCPP@,$CXXCPP,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
 s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
+s,@HAVE_NOXLOCA_TRUE@,$HAVE_NOXLOCA_TRUE,;t t
+s,@HAVE_NOXLOCA_FALSE@,$HAVE_NOXLOCA_FALSE,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
